### ISSUE TITLE
Push to Nuvola Player project

### ISSUE THREAD

**Issue by s83** [tiliado/nuvola-app-mixcloud#1]

**Comment by fenryxo** [comment]
Hi. Thanks for your work. I'll take a look at it after I finish other code reviews I have on the shelve.

**Comment by fenryxo** [comment]
Hello. Here comes code review :-)

Some minor issues:

1. Set `version_major` to `1` in `metadata.json`.
2. If you want to maintain your integration script as a part of the Nuvola Player project, your repository will be transferred under Tiliado organization account (`tiliado/nuvola-app-mixcloud`) and you will have commit access to the repository. In that case, please change URL for bug reporting in `README.md`. 

Fixes needed in integrate.js:

1. When music is paused, playback state is set to `unknown`. Set it to `paused`. (See screenshot.)
2. Album name that you script sets is not actually an album name. Set it to `null` (See screenshot.)

    ![mixcloud](https://cloud.githubusercontent.com/assets/853706/6887821/33f56e72-d66b-11e4-9b30-594ab07c3438.png)

3. I got following error in console:
    ```
    Error: undefined is not a valid argument for 'in' (evaluating 'keys[0] in obj')
    hasPath@file:///home/fenryxo/dev/repo/nuvola/apps/nuvola-app-mixcloud/integrate.js:453:22
    file:///home/fenryxo/dev/repo/nuvola/apps/nuvola-app-mixcloud/integrate.js:192:21
    $digest@https://media-mix.netdna-ssl.com/media/js2/www_js.b83080324bf8bc207661b478cb7986f5.js:2:67441
    $apply@https://media-mix.netdna-ssl.com/media/js2/www_js.b83080324bf8bc207661b478cb7986f5.js:2:68788
    https://media-mix.netdna-ssl.com/media/js2/www_js.b83080324bf8bc207661b478cb7986f5.js:2:31389
    a@https://media-mix.netdna-ssl.com/media/js2/www_js.b83080324bf8bc207661b478cb7986f5.js:1:23059
    https://media-mix.netdna-ssl.com/media/js2/www_js.b83080324bf8bc207661b478cb7986f5.js:1:44665
    r@https://media-mix.netdna-ssl.com/media/js2/www_js.b83080324bf8bc207661b478cb7986f5.js:4:54278
    nrWrapper@https://www.mixcloud.com/?preview=1:1:25969
    _sendMessageSync@[native code]
    setEnabled@file:///home/fenryxo/dev/repo/nuvolaplayer/build/share/nuvolaplayer3/js/main.js:360:35
    setCanPlay@file:///home/fenryxo/dev/repo/nuvolaplayer/build/share/nuvolaplayer3/js/main.js:559:34
    file:///home/fenryxo/dev/repo/nuvola/apps/nuvola-app-mixcloud/integrate.js:158:27
    $digest@https://media-mix.netdna-ssl.com/media/js2/www_js.b83080324bf8bc207661b478cb7986f5.js:2:67441
    $apply@https://media-mix.netdna-ssl.com/media/js2/www_js.b83080324bf8bc207661b478cb7986f5.js:2:68788
    https://media-mix.netdna-ssl.com/media/js2/www_js.b83080324bf8bc207661b478cb7986f5.js:7:20705
    t@https://media-mix.netdna-ssl.com/media/js2/www_js.b83080324bf8bc207661b478cb7986f5.js:7:13389
    success@https://media-mix.netdna-ssl.com/media/js2/www_js.b83080324bf8bc207661b478cb7986f5.js:7:13762
    r@https://media-mix.netdna-ssl.com/media/js2/www_js.b83080324bf8bc207661b478cb7986f5.js:4:54278
    l@https://ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js:4:24909
    fireWith@https://ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js:4:50440
    k@https://ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js:6:5359
    https://ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js:6:9153
    nrWrapper@https://www.mixcloud.com/?preview=1:1:25969
    ```

4. Why do you use function-level strict mode instead of global strict mode? 


Ping me when you are done :-)

**Comment by s83** [comment]
Hi @fenryxo, thank you for your feedback.
Everything is fixed. Ready to transfer the repo.
:+1:

**Comment by fenryxo** [comment]
Hi @s83 

> Everything is fixed. Ready to transfer the repo.

Great! There is a GitHub documentation about [how to transfer repository from user to an organization](https://help.github.com/articles/transferring-a-repository/#transferring-from-a-user-to-an-organization). After you will accept invitation, you will have sufficient rights to transfer the repository under [Tiliado Nuvola Mixcloud team](https://github.com/orgs/tiliado/teams/nuvola-mixcloud/repositories). Ping me when you are done and I'll create Debian/Ubuntu/Fedora packages ;-)

**Comment by s83** [comment]
Hi @fenryxo 
transfer is done, nice!

**Comment by fenryxo** [comment]
I've packaged and announced your web app script :-) If you haven't already done so:

1. Subscribe to the [Nuvola Player Development forum](https://groups.google.com/d/forum/nuvola-player-devel) as I post here announcements related to development. The traffic is pretty low, so don't afraid your inbox gets filled by tons of emails.
2. Create an account at [Tiliado.eu](https://tiliado.eu) and send me your username. I'll add you to Tiliado developers group. You can then fill in your credentials in Nuvola Player preferences not to be bothered by donate bar. Also, you will get access to all development packages of Nuvola Player as some of them are currently not publicly available.
