### ISSUE TITLE
Audio playback supported by browser, but not by MixCloud

### ISSUE THREAD

**Issue by iddo** [tiliado/nuvola-app-mixcloud#12]
Ubuntu 17.1, stopped playing with the following message:

> Sorry - your browser is not supported.
> Please update your browser or install another such as Google Chrome.
> Mixcloud requires HTML5 audio with MP3 and MP4 support.

![screenshot from 2018-02-22 12-04-34](https://user-images.githubusercontent.com/917594/36532166-aff69ff4-17c8-11e8-9909-d7c29583fd4d.png)

![screenshot from 2018-02-22 12-10-22](https://user-images.githubusercontent.com/917594/36532442-6acf3d72-17c9-11e8-813d-2c4fa937cbd8.png)

![screenshot from 2018-02-22 12-11-41](https://user-images.githubusercontent.com/917594/36532525-98ecb0d6-17c9-11e8-9e01-6f0bc2d564a9.png)

**Comment by fenryxo** [comment]
Hello @iddo. Thanks for reporting this issue. Does `flatpak run --env=NUVOLA_USE_CEF=true eu.tiliado.NuvolaAppMixcloud -D` work?

**Comment by iddo** [comment]
Yes, using this command line to start the player does fix the problem.

One more thing though: even without the above workaround, when hovering on the play button of a song listing it plays the preview correctly, while trying to actually play the song fails with the error in this bug listing, so it looks like a selective counter-feature by the mixcloud team

**Comment by fenryxo** [comment]
> Yes, using this command line to start the player does fix the problem.

Great :-) I'll update Mixcloud to require Chromium backend.

> One more thing though: even without the above workaround, when hovering on the play button of a song listing it plays the preview correctly, while trying to actually play the song fails with the error in this bug listing, so it looks like a selective counter-feature by the mixcloud team

It might be possible that the preview uses a single short stream that can be played without Media Stream Extension, whereas full songs use multiple short streams and MSE is required to combine them.

**Comment by fenryxo** [comment]
Could you run `flatpak update --system; flatpak update --user` and then check whether Mixcloud works without `NUVOLA_USE_CEF`?

**Comment by iddo** [comment]
It works.

For completeness sake, running
> flatpak run eu.tiliado.NuvolaAppMixcloud

yields the following logs

> 
> (nuvolaruntime:3): Gtk-WARNING **: Locale not supported by C library.
> 	Using the fallback 'C' locale.
> Runner: [WARNING Δ398181us Nuvola] StartupWindow.vala:170: tiliado-account-message: No Tiliado account.
> Runner: [WARNING Δ075090us Nuvola] CefEngine.vala:192: Not implemented: apply_network_proxy()
> ATTENTION: default value of option force_s3tc_enable overridden by environment.
> Worker: [DEBUG Δ022173us Nuvola] CefRendererExtension.vala:134: Got JS context
> Worker: [INFO Δ000074us CefGtk] RendererContext.vala:57: JS Context created 1
> 
> (eu.tiliado.NuvolaAppMixcloud:3): Gtk-WARNING **: Child name 'developersidebar' not found in GtkStack
> 
> (eu.tiliado.NuvolaAppMixcloud:3): Gtk-WARNING **: Unable to parse accelerator '': ignored request to install 1 accelerators
> 
> (eu.tiliado.NuvolaAppMixcloud:3): Gtk-WARNING **: Unable to parse accelerator '': ignored request to install 1 accelerators
> 
> (eu.tiliado.NuvolaAppMixcloud:3): Gtk-WARNING **: Unable to parse accelerator '': ignored request to install 1 accelerators
> Worker: [DEBUG Δ640879us Nuvola] CefRendererExtension.vala:142: Lost JS context
> Worker: [INFO Δ000144us CefGtk] RendererContext.vala:64: JS Context released: 1
> Worker: [DEBUG Δ005673us Nuvola] CefRendererExtension.vala:134: Got JS context
> Worker: [INFO Δ007023us CefGtk] RendererContext.vala:57: JS Context created 1
> Runner: [CRITICAL Δ01s397402us GLib-GIO] g_simple_action_set_state: assertion 'value != NULL' failed
> Runner: [CRITICAL Δ000033us GLib-GIO] Application will not function properly.
> [0224/115410.920001:ERROR:object_proxy.cc(573)] Failed to call method: org.gnome.SessionManager.Inhibit: object_path= /org/gnome/SessionManager: org.gnome.SessionManager.GeneralError: Application ID not specified
> [0224/115410.920072:ERROR:power_save_blocker_x11.cc(336)] No response to Inhibit() request!
> [0224/115411.237383:ERROR:object_proxy.cc(573)] Failed to call method: org.gnome.SessionManager.Uninhibit: object_path= /org/gnome/SessionManager: org.gnome.SessionManager.GeneralError: Unable to uninhibit: Invalid cookie
> [0224/115411.237418:ERROR:power_save_blocker_x11.cc(408)] No response to Uninhibit() request!
> [0224/115413.626825:ERROR:object_proxy.cc(573)] Failed to call method: org.gnome.SessionManager.Inhibit: object_path= /org/gnome/SessionManager: org.gnome.SessionManager.GeneralError: Application ID not specified
> [0224/115413.626917:ERROR:power_save_blocker_x11.cc(336)] No response to Inhibit() request!
> 

And the following header is visible on each run
![screenshot from 2018-02-24 11-57-18](https://user-images.githubusercontent.com/917594/36629095-f38d05a4-1959-11e8-8ae3-be85877f0035.png)
