### ISSUE TITLE
Add mix name as album

### ISSUE THREAD

**Issue by arcresu** [tiliado/nuvola-app-mixcloud#2]
Currently the track name and artist from the tracklist are exposed to nuvola while the album and art fields are left blank. I suggest using the name of the mix as the value for album, and the mix's art as the album art. These details are available already in `Mixcloud.scopes.PlayerQueueCtrl`.

Thanks for this integration script!

**Comment by s83** [comment]
Hello! Thank you for reporting the issue.
I will look into it as soon as possible.

**Comment by fenryxo** [comment]
Hello @arcresu & @s83. Just a few comments:

> I suggest using the name of the mix as the value for album [...]

If no real album name is present, album name metadata must be empty. It is not allowed to use a mix name or other fake album names because other components (e.g. Last FM scrobbling) assume that all metadada which have been set are correct.

> [...] the mix's art as the album art.

That's possible.

**Comment by arcresu** [comment]
The thing is that mixcloud is a little strange in that it gives both the details of the mix which is playing and the details of the track "inside" the mix (when available - which might not be for the whole duration of a mix). That doesn't fit the normal model of music metadata unless you treat the mix as an album since it's a container for tracks.

I hadn't considered lastfm, but in fact the way things stand currently is even worse from that perspective so it's not so straightforward. When the "inner" track details are unavaible the app reports the mix's details instead. In any case what is being played has often been modified from the original track in order to incorporate it into the mix.

Looking at my lastfm library:

![screenshot from 2016-05-17 18-54-36](https://cloud.githubusercontent.com/assets/322256/15316549/e7132f9e-1c60-11e6-8882-bf97607ca92e.png)

there are a mixture of entire mixes and individual "inner" tracks with duplicates all over the place (I only listened once to each mix in that period). For example the mix with name containing `Thefft - Camden Crawl` appears multiple times with constituent tracks inserted occasionally where than data was provided by mixcloud.

It's more accurate to report the entire mix's details to lastfm, however it's more useful for MPRIS interfaces to know both the mix and "inner" track details. I don't know how best to reconcile that.

**Comment by fenryxo** [comment]
> I hadn't considered lastfm, but in fact the way things stand currently is even worse from that perspective so it's not so straightforward. When the "inner" track details are unavaible the app reports the mix's details instead.

This should be fixed. Sometimes, there is a track title and an artist name above the progress bar, but script reports Mix details instead of track details. Metadata parsing should be made more robust.

![mixcloud_incorrect_track_info](https://cloud.githubusercontent.com/assets/853706/15317230/e4d9127e-1c20-11e6-83bc-21276ee0e1fb.png)

> It's more accurate to report the entire mix's details to lastfm, however it's more useful for MPRIS interfaces to know both the mix and "inner" track details. I don't know how best to reconcile that.

It isn't possible to provide different data to MPRIS component and Last.fm component. The script should reliably report either mix details or inner track details but not not mix them. How frequent is the case that inner track details are not available in the web interface?

**Comment by s83** [comment]
The inner track details not always there. Is it relevant to fallback to mix details when necessary?

**Comment by arcresu** [comment]
I'd say most mixes don't have tracklist data that covers the entire mix - there will always be gaps where there is no inner track detail. Since it's possible to report different tracks to different places then how about this:

  * **lastfm**: only ever report the mix details so that the entire mix corresponds to exactly one scrobble
  * **MPRIS etc.**: report inner track details (ideally using the mix name as the "album") and for times when it is unavailable put "Unknown track" and "Unknown artist" but continue to report the mix name in the album field.

**Comment by arcresu** [comment]
Sorry, I just realised I misread your post. Since it's NOT possible to report different things to different places, I'd say always go for the mix details, even if it's a shame to lose the inner track details.

**Comment by s83** [comment]
Hello, I fixed the track's report and the missing album arts.
The fix is available here : https://github.com/tiliado/nuvola-app-mixcloud/tree/hotfix/1.1
can you test?

**Comment by arcresu** [comment]
Great, thanks! I tested this branch and I can confirm that the album art is set
correctly and the track details are now only coming from the mix itself and not
the song within the mix.

Just remember to bump the version number in the metadata.json - I was a little
confused at first about which version I was running :P

**Comment by fenryxo** [comment]
> Just remember to bump the version number in the metadata.json

[Version number is increased only when a release is made.](https://tiliado.github.io/nuvolaplayer/development/apps/guidelines.html#releases)

**Comment by s83** [comment]
yes bumped the minor version.

**Comment by s83** [comment]
@fenryxo do you need a release request for packaging?

**Comment by fenryxo** [comment]
It's better to create a ticket for me not to forget to do the packaging. I'll probably make release 3.0 as [there seem to be 2.x releases](https://github.com/tiliado/nuvola-app-mixcloud/releases).

**Comment by fenryxo** [comment]
Released in version 3.0.
