### ISSUE TITLE
Release 1.1

### ISSUE THREAD

**Issue by s83** [tiliado/nuvola-app-mixcloud#3]
Hi @fenryxo, can you package the new release?
The fixes are related to the issue #2.
Thanks

**Comment by Celti** [comment]
You should probably integrate the new changes from nuvola-app-template before a new release makes it out the door, to make it easy for package maintainers. :)

**Comment by s83** [comment]
Thank you for pointing that @Celti. I'll bring the changes ASAP.

**Comment by fenryxo** [comment]
The icon set and related changes will be in the next release. I have them on my shelve and will make a pull request when I get down to it. However, there are more important issues right now, especially NP 3.0.3 bug fix release.

**Comment by fenryxo** [comment]
P.S. I've made release 3.0. Version 1.1 would be confusing as there are some 2.x tags in the repo.

**Comment by s83** [comment]
thank you!
