### ISSUE TITLE
Integrate the new changes from nuvola-app-template

### ISSUE THREAD

**Issue by s83** [tiliado/nuvola-app-mixcloud#5]
Hello,
I updated the app to include the changes from nuvola-app-template.
Testing branch: [tpl/upgrade](https://github.com/tiliado/nuvola-app-mixcloud/tree/tpl/upgrade)
Code review : #4 
Can you test/review?
Thank you
Samuel

**Comment by fenryxo** [comment]
Hello. No need to create tickets for pull requests.
