### ISSUE TITLE
new release

### ISSUE THREAD

**Issue by s83** [tiliado/nuvola-app-mixcloud#7]
Hi @fenryxo, can you package a new release?
Thank you

**Comment by s83** [comment]
ping @fenryxo

**Comment by fenryxo** [comment]
Hello @s83. There is one item left from tiliado/nuvolaplayer#242 - see PR #8.

**Comment by s83** [comment]
Thank you @fenryxo for pointing that. PR merged.

**Comment by fenryxo** [comment]
Packages built & uploaded. I'll announce the new release in the evening as I'm about to go jogging now. I'll close this ticket then.
