### ISSUE TITLE
Make sure Mixcloud Beta does work

### ISSUE THREAD

**Issue by fenryxo** [tiliado/nuvola-app-mixcloud#9]
Hello @s83, I've got a newsletter from Mixcloud:

> Psst, one more thing... 
> We have a new website! It's not quite ready for the public yet, but you can get exclusive early access to the beta right away. Let us know what you think and join the ride as we finalize things for a full release. 
> https://beta.mixcloud.com/

Could you take a look at it at your earliest convenience? Thanks!

**Comment by s83** [comment]
Hi, the beta is unavailable.

**Comment by fenryxo** [comment]
It is probably available only to users who were sent an invitation. Could you try [this link](https://www.mixcloud.com/pigeon/ctrz/F5RGK5DBF5VG62LOL5ZWSZ3OMVSC6P3VONSXEPLGMVXHE6LYN4TF643JM46TQVLEIZBEQS2NMNLDMV22HBVGU3BTJVUVMQ3LJBATAWI=/PCOHLDGLB2BDAECFP6CXI3IJSZBMBFL72JGMWVAH7MQLJREF6HP43MDXPHXLSOI7WGFVWIYSX2G4KCQG2JRGBW4KXA2MEZKWZ4NAGU3FLAQ6LI7AVNOWTJ73EMBILVXFZC7JZ34UFN4XEUBJU6ZQC77TS3GYEHUOKCMWTYIBI7O47HOWOJJL3FP2HJGBFOTOSRXJVPKSHAHAQIF6H6JJSNWI)?

**Comment by s83** [comment]
Yes it works, I'll take a look ;-)
I removed your link for your privacy.

**Comment by s83** [comment]
Nuvola playback and track's infos are ok for the moment.
